version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      # Montando o arquivo SQLite como volume
      - ./opwell.sqlite:/app/opwell.sqlite
      - ./logs:/app/logs
    command: >
      sh -c "yarn build &&
             yarn start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/plants"]
      interval: 30s
      timeout: 10s
      retries: 3

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:3001/docs/swagger.json
    depends_on:
      - backend